#
# This makegen template is grafted from the original Makefile (also
# included in this directory).  Look there for further porting hints
#

# Things you might want to put in ENV and LENV:
# -Dvoid=int		compilers that don't do void
# -DCHARBITS=0377	compilers that don't do unsigned char
# -DSTATIC=extern	compilers that don't like "static foo();" as forward dec
# -DSTRCSPN		library does not have strcspn()
# -Dstrchr=index	library does not have strchr()

CC_OPT= -O
ENV=
LENV=-Dvoid=int -DCHARBITS=0377


CC_FLAGS= $(CFLAGS) $(ENV) -I.
LINT_FLAGS= $(LINTFLAGS) $(ENV) -I.

!library_unix libregexp.a regexp.c,regsub.c
!library_os2 libregexp.a regexp.c,regsub.c

!libinstall libregexp.a $(INST_DIR)/lib/libregexp.a 744 $(ROOT)
!install regexp.h $(INST_DIR)/include/regexp.h 744 $(ROOT)


all : libregexp.a
