
!directory broker all,clean,install
!directory index all,clean,install
!directory lock all,clean,install
!directory regexp all,clean,install
!directory cra all,clean,install

!directory main all,clean,install
